title: "OCI Terraform  Configuration "
description: "Stack to deploy VPN in OCI Tenancy"
stackDescription: "Stack to deploy VPN in OCI Tenancy"
schemaVersion: 1.1.0
version: "20201125"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - user_ocid
  - fingerprint
  - private_key_path
  - region
  

- title: "Required Configuration"
  visible: true  
  variables:
  - customer_label
  - show_advanced 

- title: "VPN  Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - compartment_id
  - drg_id
  - v1_cl_vpn
  - v1_cw_vpn
  - cust1_vpn
  - cust2_vpn
  - v1_cl_domain
  - v1_cw_domain
  - cust1_domain
  - cust2_domain
  - access

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false


  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region where you deploy your application"
    type: oci:identity:region:name
    required: true
    visibile: true
  
  customer_label:
    title: "customer label"
    description: "Label used as a prefix for naming resources"
    type: string
    required: true
    visible: true

  compartment_id:
    title: "Compartment OCID"
    description: "Choose Comparment where you deploy your vpn"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  drg_id:
    title: "Compartment DRG"
    description: "DRG"
    type: oci:identity:dynamicroutegateway:id
    required: true
    visibile: true
    dependsOn: 
      compartmentId: ${compartment_id}

  

# VPN Configuration

  v1_cl_vpn:
    type: string
    required: false
    default: "95.45.180.36"
    title: "CL VPN"
    description: "CL VPN"

  v1_cw_vpn:
    type: string
    required: false
    default: "159.134.94.228"
    title: "CW VPN"
    description: "CW VPN"

  cust1_vpn:
    type: string
    required: false
    default: "109.159.193.202"
    title: "cust VPN "
    description: "cust VPN"

  cust2_vpn:
    type: string
    required: false
    default: "109.159.193.203"
    title: "cust VPN"
    description: "cust VPN"

  v1_cl_domain: 
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "CIDR Blocks for v1 vpns"
    description: "CIDR Blocks for v1 vpns"
    default: []


  v1_cw_domain: 
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "CIDR Blocks for customer vpns"
    description: "CIDR Blocks for customer vpns"
    default: []

  cust1_domain: 
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "CIDR Blocks for customer domain"
    description: "CIDR Blocks for customer domain"
    default: []


  cust2_domain:
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "v1_domains "
    description: "v1_domains"
    default: []

  access:
    type: array
    items:
      type: string
    uniqueItems: true
    required: false
    maxItems: 9
    minItems: 1
    title: "Access IPs "
    description: "Access IPs"
    default: []

